[buildPlans.iosevka-rofrol]
family = "Iosevka Rofrol"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigations = true

  [buildPlans.iosevka-rofrol.variants]
  inherits = "ss08"

    [buildPlans.iosevka-rofrol.variants.design]
    capital-a = "straight-serifless"
    capital-i = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-n = "standard-serifless"
    capital-r = "straight-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "serifless"
    g = "double-storey"
    i = "tailed-serifed"
    j = "serifed"
    k = "symmetric-connected-serifless"
    l = "tailed-serifed"
    v = "straight-serifless"
    w = "straight-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"
    zero = "slashed"
    two = "straight-neck-serifless"
    four = "closed-serifless"
    six = "straight-bar"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "hex-mid"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    at = "threefold"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "smooth"

[buildPlans.iosevka-rofrol.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-rofrol.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rofrol.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-rofrol-zed]
family = "Iosevka Rofrol Zed"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigations = true

  [buildPlans.iosevka-rofrol-zed.variants]
  inherits = "ss08"

    [buildPlans.iosevka-rofrol-zed.variants.design]
    capital-w = "curly-serifless"
    capital-x = "straight-serifless"
    f = "serifless"
    g = "double-storey"
    l = "serifed"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    zero = "slashed"
    four = "semi-open-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "penta-high"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    at = "threefold"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"

[buildPlans.iosevka-rofrol-zed.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-rofrol-zed.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rofrol-zed.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
