# https://github.com/be5invis/Iosevka/blob/main/private-build-plans.sample.toml

### See https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md for comprehensive
### documentation of the options in this file

[buildPlans.iosevka-rofrol]
family = "Iosevka Rofrol"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigations = true

  [buildPlans.iosevka-rofrol.variants]
  inherits = "ss08"

    [buildPlans.iosevka-rofrol.variants.design]
    capital-a = "straight-serifless"
    capital-i = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-n = "standard-serifless"
    capital-r = "straight-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "flat-hook-serifless"
    g = "double-storey"
    i = "serifed-flat-tailed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    t = "flat-hook"
    v = "straight-serifless"
    w = "straight-serifless"
    x = "straight-serifless"
    y = "straight-turn-serifless"
    z = "straight-serifless"
    zero = "slashed"
    two = "straight-neck-serifless"
    four = "closed-serifless"
    six = "straight-bar"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "hex-mid"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    at = "threefold"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "smooth"

[buildPlans.iosevka-rofrol.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-rofrol.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rofrol.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-rofrol-zed]
family = "Iosevka Rofrol Zed"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigations = true

  [buildPlans.iosevka-rofrol-zed.variants]
  inherits = "ss08"

    [buildPlans.iosevka-rofrol-zed.variants.design]
    capital-w = "curly-serifless"
    capital-x = "straight-serifless"
    f = "serifless"
    g = "double-storey"
    l = "serifed"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    zero = "slashed"
    four = "semi-open-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "penta-high"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    at = "threefold"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"

[buildPlans.iosevka-rofrol-zed.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-rofrol-zed.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rofrol-zed.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-rofrol-curled]
family = "Iosevka Rofrol Curled"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigations = true

  [buildPlans.iosevka-rofrol-curled.variants]
  inherits = "ss08"

    [buildPlans.iosevka-rofrol-curled.variants.design]
    capital-a = "straight-serifless"
    capital-i = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-n = "standard-serifless"
    capital-r = "straight-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "serifless"
    g = "double-storey"
    i = "tailed-serifed"
    j = "serifed"
    k = "symmetric-connected-serifless"
    l = "tailed-serifed"
    v = "straight-serifless"
    w = "straight-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"
    zero = "slashed"
    two = "straight-neck-serifless"
    four = "closed-serifless"
    six = "straight-bar"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "hex-mid"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    at = "threefold"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "smooth"

[buildPlans.iosevka-rofrol-curled.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-rofrol-curled.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rofrol-curled.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-rofrol-zed2]      # <iosevka-rofrol-zed2> is your plan name
family = "Iosevka Rofrol Zed2"        # Font menu family name
spacing = "fixed"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"                  # Optional; Values: `sans` or `slab`
exportGlyphNames = false       # Set this to true for ligature support in Kitty (increased file size)

###################################################################################################
# Configure variants

# Optional; Whether to inherit a `ss##` variant
[buildPlans.iosevka-rofrol-zed2.variants]
inherits = "ss08"

# Optional; Configure single character's variant
[buildPlans.iosevka-rofrol-zed2.variants.design]
capital-a = "straight-serifless"
capital-i = "serifed"
capital-k = "symmetric-connected-serifless"
capital-n = "standard-serifless"
capital-r = "straight-serifless"
capital-v = "straight-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
f = "serifless"
g = "double-storey"
k = "symmetric-connected-serifless"
l = "serifed"
v = "straight-serifless"
w = "straight-serifless"
x = "straight-serifless"
y = "straight-turn-serifless"
z = "straight-serifless"
zero = "slashed"
two = "straight-neck-serifless"
four = "closed-serifless"
six = "straight-bar"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-high"
underscore = "above-baseline"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
at = "threefold"
dollar = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"

# End variant section

###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.


[buildPlans.iosevka-rofrol-zed2.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.iosevka-rofrol-zed2.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.iosevka-rofrol-zed2.weights.Light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-rofrol-zed2.weights.SemiLight]
shape = 350
menu  = 350
css   = 350

[buildPlans.iosevka-rofrol-zed2.weights.Regular]
shape = 400  # Weight for glyph shapes.
menu  = 400  # Weight for the font's names.
css   = 400  # Weight for webfont CSS.

[buildPlans.iosevka-rofrol-zed2.weights.Book]
shape = 450
menu  = 450  # Use 450 here to name the font's weight "Book"
css   = 450

[buildPlans.iosevka-rofrol-zed2.weights.Bold]
shape = 700
menu  = 700
css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slope sets
# When this section is absent, all slopes would be built.

[buildPlans.iosevka-rofrol-zed2.slopes.Upright]
angle = 0             # Angle in degrees. Valid range [0, 15]
shape = "upright"     # Slope grade used for shape selection.  `upright` | `oblique` | `italic`
menu  = "upright"     # Slope grade used for naming.           `upright` | `oblique` | `italic`
css   = "normal"      # Slope grade used for webfont CSS.      `normal`  | `oblique` | `italic`

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.iosevka-rofrol-zed2.widths.Extended]
shape = 450
menu  = 7
css   = "expanded"
