[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants]
inherits = "ss08"

[buildPlans.IosevkaCustom.variants.design]
# capital-n = "standard"
capital-w = "curly-serifless"
capital-x = "straight-serifless"
g = "double-storey"
x = "curly-serifless"
y = "straight-turn-serifless"
# eszet = "sulzbacher-descending"
zero = "slashed"
four = "semi-open-serifless"
# five = "vertical-upper-left-bar"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-high"
underscore = "above-baseline"
caret = "medium"
paren = "normal"
brace = "curly"
number-sign = "slanted"
ampersand = "closed"
dollar = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400
