[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss08"

    [buildPlans.IosevkaCustom.variants.design]
    capital-w = "curly-serifless"
    capital-x = "straight-serifless"
    g = "double-storey"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    zero = "slashed"
    four = "semi-open-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "penta-high"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

# inspired by
# https://github.com/be5invis/Iosevka/issues/132#issuecomment-370163262
# https://github.com/protesilaos/iosevka-comfy/blob/9850b5320ecb460399bf3d007a95aff18628b13e/private-build-plans.toml#L726
[buildPlans.IosevkaCustom.widths.Normal]
shape = 550
menu = 5
css = "normal"

# needed to not build Oblique and Italic
[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
