[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-i = "short-serifed"
capital-j = "serifless"
capital-q = "straight"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-y = "curly-serifless"
a = "double-storey-serifless"
f = "serifless"
g = "double-storey"
i = "serifed"
j = "serifed"
l = "serifed"
m = "serifless"
t = "bent-hook"
v = "curly-serifless"
w = "curly-serifless"
y = "straight-turn-serifless"
cyrl-u = "straight-motion-serifed"
one = "no-base"
two = "curly-neck-serifless"
three = "two-arcs"
four = "semi-open-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "straight-serifed"
eight = "two-circles"
asterisk = "penta-high"
paren = "normal"
brace = "curly"
number-sign = "slanted"
at = "threefold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
question = "corner"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
