[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
capital-b = "more-asymmetric-serifless"
capital-j = "serifless"
capital-w = "straight-vertical-sides-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
i = "semi-tailed"
j = "flat-hook-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
t = "flat-hook"
one = "no-base"
two = "straight-neck-serifless"
three = "two-arcs"
four = "closed-serifless"
five = "oblique-flat-serifless"
asterisk = "penta-mid"
paren = "normal"
brace = "straight"
at = "threefold"
dollar = "open"
percent = "rings-continuous-slash"
question = "smooth"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
